// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/room.proto

package chatproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,2,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Index          int32                  `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	LastMessageAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Room) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Room) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomsResponse) Reset() {
	*x = RoomsResponse{}
	mi := &file_proto_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsResponse) ProtoMessage() {}

func (x *RoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsResponse.ProtoReflect.Descriptor instead.
func (*RoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomId           *string                `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content          *MessageContent        `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ReplyToMessageId *string                `protobuf:"bytes,4,opt,name=reply_to_message_id,json=replyToMessageId,proto3,oneof" json:"reply_to_message_id,omitempty"`
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ParticipantIds   []string               `protobuf:"bytes,7,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetReplyToMessageId() string {
	if x != nil && x.ReplyToMessageId != nil {
		return *x.ReplyToMessageId
	}
	return ""
}

func (x *SendMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendMessageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SendMessageRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type MessagesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId *string                `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*MessagesRequest_SendMessageRequest
	Request       isMessagesRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesRequest) Reset() {
	*x = MessagesRequest{}
	mi := &file_proto_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesRequest) ProtoMessage() {}

func (x *MessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesRequest.ProtoReflect.Descriptor instead.
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4}
}

func (x *MessagesRequest) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

func (x *MessagesRequest) GetRequest() isMessagesRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MessagesRequest) GetSendMessageRequest() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Request.(*MessagesRequest_SendMessageRequest); ok {
			return x.SendMessageRequest
		}
	}
	return nil
}

type isMessagesRequest_Request interface {
	isMessagesRequest_Request()
}

type MessagesRequest_SendMessageRequest struct {
	SendMessageRequest *SendMessageRequest `protobuf:"bytes,2,opt,name=send_message_request,json=sendMessageRequest,proto3,oneof"`
}

func (*MessagesRequest_SendMessageRequest) isMessagesRequest_Request() {}

type MessagesResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*MessagesResponse_Message
	Response      isMessagesResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesResponse) Reset() {
	*x = MessagesResponse{}
	mi := &file_proto_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesResponse) ProtoMessage() {}

func (x *MessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesResponse.ProtoReflect.Descriptor instead.
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{5}
}

func (x *MessagesResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagesResponse) GetResponse() isMessagesResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MessagesResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Response.(*MessagesResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

type isMessagesResponse_Response interface {
	isMessagesResponse_Response()
}

type MessagesResponse_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

func (*MessagesResponse_Message) isMessagesResponse_Response() {}

var File_proto_room_proto protoreflect.FileDescriptor

const file_proto_room_proto_rawDesc = "" +
	"\n" +
	"\x10proto/room.proto\x12\tchatproto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13proto/message.proto\"\x94\x03\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\tR\x0eparticipantIds\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x05R\x05index\x12B\n" +
	"\x0flast_message_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at\"\x1f\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\rRoomsResponse\x12%\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0f.chatproto.RoomR\x05rooms\"\xbd\x02\n" +
	"\x12SendMessageRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\tH\x00R\x06roomId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x123\n" +
	"\acontent\x18\x03 \x01(\v2\x19.chatproto.MessageContentR\acontent\x122\n" +
	"\x13reply_to_message_id\x18\x04 \x01(\tH\x01R\x10replyToMessageId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12'\n" +
	"\x0fparticipant_ids\x18\a \x03(\tR\x0eparticipantIdsB\n" +
	"\n" +
	"\b_room_idB\x16\n" +
	"\x14_reply_to_message_id\"\x99\x01\n" +
	"\x0fMessagesRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\tH\x01R\x06roomId\x88\x01\x01\x12Q\n" +
	"\x14send_message_request\x18\x02 \x01(\v2\x1d.chatproto.SendMessageRequestH\x00R\x12sendMessageRequestB\t\n" +
	"\arequestB\n" +
	"\n" +
	"\b_room_id\"g\n" +
	"\x10MessagesResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12.\n" +
	"\amessage\x18\x02 \x01(\v2\x12.chatproto.MessageH\x00R\amessageB\n" +
	"\n" +
	"\bresponse2\xec\x01\n" +
	"\x0eChatController\x124\n" +
	"\x05Rooms\x12\x0f.chatproto.User\x1a\x18.chatproto.RoomsResponse0\x01\x12[\n" +
	"\fListMessages\x12$.chatproto.ListMessagesServerRequest\x1a%.chatproto.ListMessagesServerResponse\x12G\n" +
	"\bMessages\x12\x1a.chatproto.MessagesRequest\x1a\x1b.chatproto.MessagesResponse(\x010\x01B\fZ\n" +
	"/chatprotob\x06proto3"

var (
	file_proto_room_proto_rawDescOnce sync.Once
	file_proto_room_proto_rawDescData []byte
)

func file_proto_room_proto_rawDescGZIP() []byte {
	file_proto_room_proto_rawDescOnce.Do(func() {
		file_proto_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_proto_rawDesc), len(file_proto_room_proto_rawDesc)))
	})
	return file_proto_room_proto_rawDescData
}

var file_proto_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_room_proto_goTypes = []any{
	(*Room)(nil),                       // 0: chatproto.Room
	(*User)(nil),                       // 1: chatproto.User
	(*RoomsResponse)(nil),              // 2: chatproto.RoomsResponse
	(*SendMessageRequest)(nil),         // 3: chatproto.SendMessageRequest
	(*MessagesRequest)(nil),            // 4: chatproto.MessagesRequest
	(*MessagesResponse)(nil),           // 5: chatproto.MessagesResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*MessageContent)(nil),             // 7: chatproto.MessageContent
	(*Message)(nil),                    // 8: chatproto.Message
	(*ListMessagesServerRequest)(nil),  // 9: chatproto.ListMessagesServerRequest
	(*ListMessagesServerResponse)(nil), // 10: chatproto.ListMessagesServerResponse
}
var file_proto_room_proto_depIdxs = []int32{
	6,  // 0: chatproto.Room.last_message_at:type_name -> google.protobuf.Timestamp
	6,  // 1: chatproto.Room.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: chatproto.Room.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 3: chatproto.Room.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: chatproto.RoomsResponse.rooms:type_name -> chatproto.Room
	7,  // 5: chatproto.SendMessageRequest.content:type_name -> chatproto.MessageContent
	3,  // 6: chatproto.MessagesRequest.send_message_request:type_name -> chatproto.SendMessageRequest
	8,  // 7: chatproto.MessagesResponse.message:type_name -> chatproto.Message
	1,  // 8: chatproto.ChatController.Rooms:input_type -> chatproto.User
	9,  // 9: chatproto.ChatController.ListMessages:input_type -> chatproto.ListMessagesServerRequest
	4,  // 10: chatproto.ChatController.Messages:input_type -> chatproto.MessagesRequest
	2,  // 11: chatproto.ChatController.Rooms:output_type -> chatproto.RoomsResponse
	10, // 12: chatproto.ChatController.ListMessages:output_type -> chatproto.ListMessagesServerResponse
	5,  // 13: chatproto.ChatController.Messages:output_type -> chatproto.MessagesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_room_proto_init() }
func file_proto_room_proto_init() {
	if File_proto_room_proto != nil {
		return
	}
	file_proto_message_proto_init()
	file_proto_room_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_room_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_room_proto_msgTypes[4].OneofWrappers = []any{
		(*MessagesRequest_SendMessageRequest)(nil),
	}
	file_proto_room_proto_msgTypes[5].OneofWrappers = []any{
		(*MessagesResponse_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_proto_rawDesc), len(file_proto_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_proto_goTypes,
		DependencyIndexes: file_proto_room_proto_depIdxs,
		MessageInfos:      file_proto_room_proto_msgTypes,
	}.Build()
	File_proto_room_proto = out.File
	file_proto_room_proto_goTypes = nil
	file_proto_room_proto_depIdxs = nil
}
